### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by zhaoguangyao** [wzell/cmd#6]
Exception: Need to call `set_layer` on ActivityRegularizer instance before calling the instance.
---
Hi Werner Zellinger:
something wrong happens while running exp_amazon_review.py
error happens while run amazon_review_mmatch.py

encoded_s = encoding(input_s)
encoded_t = encoding(input_t)

I know that domain_regularizer need run set_layer. However,I did not find any code about set_layer.

**Comment by wzell** [comment]
Hello zhaoguangyao,

nice to see your interest in our project!

A similar issue (and related ones) appeared in our extension of the CMD approach: [set_layer issue](https://github.com/wzell/mann/issues/5)

Please see if you can get help there.

**Comment by wzell** [comment]
seems to be a version conflict as stated in aboves issue
